package me.fritz.seattlesummer;

import me.fritz.seattlesummer.SeattleSummer;
import me.fritz.seattlesummer.RainTimers;

import org.bukkit.World;
import org.bukkit.event.weather.WeatherChangeEvent;
import org.bukkit.event.weather.WeatherListener;

/** Listens for changes in weather state
*
* @author Fritz
*
*/
public class SeattleSummerWeatherListener extends WeatherListener {
	private static SeattleSummer plugin;
	private RainTimers rainTimers;
	
	/** Listens for changes in weather state
	 * 
	 * @param instance the main SeattleSummer instance.
	 */
	public SeattleSummerWeatherListener(SeattleSummer instance) {
		plugin = instance;
		rainTimers = new RainTimers(plugin);
	}
	
	/** Called by the bukkit plugin manager whenever the weather changes
	 * 
	 * @event WeatherListenerEvent generated by bukkit
	 */
	public void onWeatherChange(WeatherChangeEvent event){
		World world = event.getWorld();
		
		if (plugin.config.isManaged(world.getName())) {
			if (event.toWeatherState()) {
				rainTimers.start(world);
			}
			else {
				rainTimers.cancel(world);
			}
		}
	}
}